import { employeesColumns } from "@/components/pes-custom/table-columns/employeesColumns";
import { DataTable } from "@/components/ui/data-table";
import { Employee } from "@/lib/types";

async function getData(): Promise<Employee[]> {
  // Fetch data from your API here.
  // Must fit the type definition to be inserted into the table
  return [
    {
      id: "E001",
      nid: "N12345",
      family_id: "F001",
      name: "John Doe",
      gender: "Male",
      date_of_birth: "1988-05-10",
      parent_name: "Jane Doe",
      email: "john.doe@example.com",
      mobile_number: "1234567890",
      whatsapp_number: "1234567890",
      address: "123 Main St, Cityville",
      religion: "Christianity",
      blood_group: "A+",
      diseases: "None",
      date_of_join: "2015-03-01",
      is_active: "Yes",
      promo_code: "PROMO2024",
      timezone: "GMT-5",
      language: "English",
      password: "johnpass123",
      salary: 60000,
      experience: "8 years",
      education: "Bachelor's in Computer Science",
      role: "Software Engineer",
    },
    {
      id: "E002",
      nid: "N23456",
      name: "Alice Smith",
      gender: "Female",
      date_of_birth: "1992-07-22",
      parent_name: "Mark Smith",
      email: "alice.smith@example.com",
      mobile_number: "0987654321",
      whatsapp_number: "0987654321",
      address: "456 Elm St, Townsville",
      religion: "Islam",
      blood_group: "O+",
      diseases: "None",
      date_of_join: "2018-09-10",
      is_active: "Yes",
      referral_code: "REF2023",
      image: "alice.jpg",
      timezone: "GMT+2",
      language: "English",
      password: "alicepass456",
      salary: 75000,
      experience: "5 years",
      education: "Master's in Data Science",
      role: "Data Scientist",
    },
    {
      id: "E003",
      nid: "N34567",
      name: "Robert Lee",
      gender: "Male",
      date_of_birth: "1985-11-12",
      parent_name: "Susan Lee",
      email: "robert.lee@example.com",
      mobile_number: "1112223333",
      whatsapp_number: "1112223333",
      address: "789 Oak St, Villagetown",
      religion: "Buddhism",
      blood_group: "B+",
      date_of_join: "2012-06-20",
      is_active: "Yes",
      timezone: "GMT-7",
      language: "English",
      password: "robertpass789",
      salary: 90000,
      experience: "12 years",
      education: "Bachelor's in Mechanical Engineering",
      role: "Mechanical Engineer",
    },
    {
      id: "E004",
      nid: "N45678",
      family_id: "F002",
      name: "Emily Johnson",
      gender: "Female",
      date_of_birth: "1990-01-15",
      parent_name: "Thomas Johnson",
      email: "emily.johnson@example.com",
      mobile_number: "2223334444",
      whatsapp_number: "2223334444",
      address: "321 Maple St, Smallville",
      blood_group: "AB+",
      diseases: "Asthma",
      date_of_join: "2016-04-01",
      is_active: "Yes",
      timezone: "GMT+1",
      language: "French",
      password: "emilypass321",
      salary: 65000,
      experience: "7 years",
      education: "Master's in Business Administration",
      role: "Project Manager",
    },
    {
      id: "E005",
      nid: "N56789",
      name: "Michael Brown",
      gender: "Male",
      date_of_birth: "1983-02-25",
      parent_name: "Laura Brown",
      email: "michael.brown@example.com",
      mobile_number: "3334445555",
      whatsapp_number: "3334445555",
      address: "654 Birch St, Metropolis",
      religion: "Christianity",
      blood_group: "O-",
      date_of_join: "2010-01-20",
      is_active: "Yes",
      timezone: "GMT-8",
      language: "English",
      password: "michaelpass654",
      salary: 85000,
      experience: "14 years",
      education: "Bachelor's in Civil Engineering",
      role: "Civil Engineer",
    },
    {
      id: "E006",
      nid: "N67890",
      name: "Sophia Williams",
      gender: "Female",
      date_of_birth: "1995-12-01",
      parent_name: "Patrick Williams",
      email: "sophia.williams@example.com",
      mobile_number: "4445556666",
      whatsapp_number: "4445556666",
      address: "987 Pine St, Lakeview",
      religion: "Hinduism",
      blood_group: "A-",
      date_of_join: "2019-07-15",
      is_active: "Yes",
      timezone: "GMT+5",
      language: "Hindi",
      password: "sophiapass987",
      salary: 72000,
      experience: "4 years",
      education: "Bachelor's in Information Technology",
      role: "System Analyst",
    },
    {
      id: "E007",
      nid: "N78901",
      name: "Daniel Martinez",
      gender: "Male",
      date_of_birth: "1993-09-10",
      parent_name: "Carlos Martinez",
      email: "daniel.martinez@example.com",
      mobile_number: "5556667777",
      whatsapp_number: "5556667777",
      address: "246 Cedar St, Rivertown",
      religion: "Christianity",
      blood_group: "B-",
      date_of_join: "2020-11-05",
      is_active: "Yes",
      timezone: "GMT-6",
      language: "Spanish",
      password: "danielpass246",
      salary: 68000,
      experience: "3 years",
      education: "Bachelor's in Electrical Engineering",
      role: "Electrical Engineer",
    },
    {
      id: "E008",
      nid: "N89012",
      name: "Olivia Davis",
      gender: "Female",
      date_of_birth: "1987-06-30",
      parent_name: "Richard Davis",
      email: "olivia.davis@example.com",
      mobile_number: "6667778888",
      whatsapp_number: "6667778888",
      address: "135 Willow St, Greendale",
      blood_group: "AB",
      date_of_join: "2014-09-10",
      is_active: "Yes",
      timezone: "GMT+3",
      language: "Arabic",
      password: "oliviapass135",
      salary: 78000,
      experience: "9 years",
      education: "Bachelor's in Finance",
      role: "Financial Analyst",
    },
    {
      id: "E009",
      nid: "N90123",
      name: "Liam Garcia",
      gender: "Male",
      date_of_birth: "1998-03-15",
      parent_name: "Maria Garcia",
      email: "liam.garcia@example.com",
      mobile_number: "7778889999",
      whatsapp_number: "7778889999",
      address: "159 Oak St, Hillside",
      blood_group: "O+",
      date_of_join: "2021-03-20",
      is_active: "Yes",
      timezone: "GMT+4",
      language: "English",
      password: "liampass159",
      salary: 62000,
      experience: "2 years",
      education: "Bachelor's in Computer Science",
      role: "Junior Developer",
    },
    {
      id: "E010",
      nid: "N01234",
      name: "Emma Taylor",
      gender: "Female",
      date_of_birth: "1991-11-20",
      parent_name: "James Taylor",
      email: "emma.taylor@example.com",
      mobile_number: "8889990000",
      whatsapp_number: "8889990000",
      address: "357 Spruce St, Riverwood",
      religion: "Judaism",
      blood_group: "A+",
      diseases: "None",
      date_of_join: "2017-02-12",
      is_active: "Yes",
      timezone: "GMT+2",
      language: "Hebrew",
      password: "emmapass357",
      salary: 70000,
      experience: "6 years",
      education: "Master's in Marketing",
      role: "Marketing Manager",
    },
    // ...
  ];
}

export default async function EmployeesPage() {
  const data = await getData();

  return (
    <div className="dashboard-tab-wrapper">
      <h3 className="text-h3">Employees</h3>
      <DataTable columns={employeesColumns} data={data} />
    </div>
  );
}
