import {
  Admin,
  AssignedFreeSession,
  Assignment,
  AssignmentSubmission,
  Attendance,
  AttendedFreeSession,
  Booking,
  Branch,
  Card,
  Class,
  ClassMapping,
  Contact,
  ContactApplication,
  Employee,
  EmployeeAttendance,
  exampleObject,
  Family,
  Fee,
  Franchise,
  FreeSession,
  Grade,
  Instructor,
  InstructorCalled,
  News,
  NewsletterSubscription,
  Parent,
  Partnership,
  PendingInstructor,
  Program,
  Review,
  Roles,
  Schedules,
  SchoolApplication,
  Student,
  Subject,
  Subscription,
  Track,
  UserRoleMapping,
} from "./types-backend-data";

export const exampleData: exampleObject[] = [
  {
    one: "Primary text",
    two: "Primary text",
    three: 5000,
    four: "Primary text",
    five: 2333,
  },
  {
    one: "Primary text",
    two: "Primary text",
    three: 5000,
    four: "Primary text",
    five: 2333,
  },
  {
    one: "Primary text",
    two: "Primary text",
    three: 5000,
    four: "Primary text",
    five: 2333,
  },
  {
    one: "Primary text",
    two: "Primary text",
    three: 5000,
    four: "Primary text",
    five: 2333,
  },
  {
    one: "Primary text",
    two: "Primary text",
    three: 5000,
    four: "Primary text",
    five: 2333,
  },
];

export const newsArray: News[] = [
  { id: "1", media: "image1.jpg", content: "Breaking news content 1" },
  { id: "2", media: "image2.jpg", content: "Breaking news content 2" },
  { id: "3", media: "image3.jpg", content: "Breaking news content 3" },
  { id: "4", media: "image4.jpg", content: "Breaking news content 4" },
  { id: "5", media: "image5.jpg", content: "Breaking news content 5" },
];

export const partnerships: Partnership[] = [
  { id: "1", partner_name: "Partner1", partner_logo: "logo1.png" },
  { id: "2", partner_name: "Partner2", partner_logo: "logo2.png" },
  { id: "3", partner_name: "Partner3", partner_logo: "logo3.png" },
  { id: "4", partner_name: "Partner4", partner_logo: "logo4.png" },
  { id: "5", partner_name: "Partner5", partner_logo: "logo5.png" },
];

export const reviews: Review[] = [
  {
    id: "1",
    full_name: "Alice Johnson",
    email: "alice@example.com",
    job: "Engineer",
    rating: "5",
    description: "Excellent service!",
    status: "Published",
  },
  {
    id: "2",
    full_name: "Bob Williams",
    email: "bob@example.com",
    job: "Designer",
    rating: "4",
    description: "Great experience!",
    status: "Published",
  },
  {
    id: "3",
    full_name: "Clara Davis",
    email: "clara@example.com",
    job: "Teacher",
    rating: "3",
    description: "Good, but needs improvement.",
    status: "Pending",
  },
  {
    id: "4",
    full_name: "David Miller",
    email: "david@example.com",
    job: "Artist",
    rating: "4",
    description: "I loved the service.",
    status: "Published",
  },
  {
    id: "5",
    full_name: "Eva Green",
    email: "eva@example.com",
    job: "Doctor",
    rating: "5",
    description: "Fantastic experience!",
    status: "Published",
  },
];

export const schoolApplications: SchoolApplication[] = [
  {
    id: "1",
    school_name: "ABC School",
    contact_person: "Mr. Smith",
    mobile_number: "555-1111",
    plans: "Expansion",
    proficiency_level: "Intermediate",
    budget: "50000",
    grades: "1-5",
    capacity: "500",
    expectations: "High-quality facilities",
  },
  {
    id: "2",
    school_name: "XYZ Academy",
    contact_person: "Ms. Johnson",
    mobile_number: "555-2222",
    plans: "Digital upgrade",
    proficiency_level: "Advanced",
    budget: "80000",
    grades: "6-8",
    capacity: "600",
    expectations: "State-of-the-art classrooms",
  },
  {
    id: "3",
    school_name: "Modern Learning Center",
    contact_person: "Mr. Clark",
    mobile_number: "555-3333",
    plans: "New Curriculum",
    proficiency_level: "Beginner",
    budget: "30000",
    grades: "1-3",
    capacity: "200",
    expectations: "High student engagement",
  },
  {
    id: "4",
    school_name: "Global Academy",
    contact_person: "Ms. Baker",
    mobile_number: "555-4444",
    plans: "STEM Program",
    proficiency_level: "Advanced",
    budget: "100000",
    grades: "9-12",
    capacity: "1000",
    expectations: "Innovative technology",
  },
  {
    id: "5",
    school_name: "Elite Scholars School",
    contact_person: "Dr. Hill",
    mobile_number: "555-5555",
    plans: "Sports facilities",
    proficiency_level: "Intermediate",
    budget: "60000",
    grades: "4-6",
    capacity: "700",
    expectations: "Comprehensive facilities",
  },
];

export const contactApplications: ContactApplication[] = [
  {
    id: "1",
    name: "Tom Harris",
    mobile_number: "555-2222",
    email: "tom@example.com",
    subject: "Partnership",
    city: "New York",
    street: "5th Avenue",
    postcode: "10001",
    idea: "Looking for collaboration",
  },
  {
    id: "2",
    name: "Susan Clark",
    mobile_number: "555-3333",
    email: "susan@example.com",
    subject: "Support Request",
    city: "Los Angeles",
    street: "Sunset Blvd",
    postcode: "90001",
    idea: "Need technical support",
  },
  {
    id: "3",
    name: "Michael Adams",
    mobile_number: "555-4444",
    email: "michael@example.com",
    subject: "Business Inquiry",
    city: "Chicago",
    street: "Michigan Avenue",
    postcode: "60601",
    idea: "Looking for business opportunities",
  },
  {
    id: "4",
    name: "Jessica White",
    mobile_number: "555-5555",
    email: "jessica@example.com",
    subject: "Feedback",
    city: "San Francisco",
    street: "Market Street",
    postcode: "94101",
    idea: "Suggestions for improvement",
  },
  {
    id: "5",
    name: "David Brown",
    mobile_number: "555-6666",
    email: "david@example.com",
    subject: "Job Application",
    city: "Miami",
    street: "Ocean Drive",
    postcode: "33101",
    idea: "Interested in job opportunities",
  },
];

export const newsletterSubscriptions: NewsletterSubscription[] = [
  { id: "1", email: "subscriber1@example.com" },
  { id: "2", email: "subscriber2@example.com" },
  { id: "3", email: "subscriber3@example.com" },
  { id: "4", email: "subscriber4@example.com" },
  { id: "5", email: "subscriber5@example.com" },
];

export const franchises: Franchise[] = [
  {
    id: "1",
    name: "Franchise A",
    owner_profession: "Entrepreneur",
    location: "New York",
    budget: "100000",
    motivation: "Expand business",
    expectations: "Great support",
    connection_type: "Direct",
    requirement_stage: "Completed",
    comments: "Looking forward to it",
    email: "owner@example.com",
    mobile_number: "555-3333",
    city: "New York",
    country: "USA",
  },
  {
    id: "2",
    name: "Franchise B",
    owner_profession: "Investor",
    location: "Los Angeles",
    budget: "200000",
    motivation: "High ROI",
    expectations: "Quick returns",
    connection_type: "Franchise",
    requirement_stage: "In Progress",
    comments: "Ready to invest",
    email: "ownerB@example.com",
    mobile_number: "555-4444",
    city: "Los Angeles",
    country: "USA",
  },
  {
    id: "3",
    name: "Franchise C",
    owner_profession: "Businessman",
    location: "Chicago",
    budget: "150000",
    motivation: "Expand network",
    expectations: "Comprehensive support",
    connection_type: "Joint Venture",
    requirement_stage: "Completed",
    comments: "Excited about the opportunity",
    email: "ownerC@example.com",
    mobile_number: "555-5555",
    city: "Chicago",
    country: "USA",
  },
  {
    id: "4",
    name: "Franchise D",
    owner_profession: "Tech Enthusiast",
    location: "San Francisco",
    budget: "250000",
    motivation: "Innovate",
    expectations: "Technology-driven",
    connection_type: "Franchise",
    requirement_stage: "Completed",
    comments: "Looking for growth",
    email: "ownerD@example.com",
    mobile_number: "555-6666",
    city: "San Francisco",
    country: "USA",
  },
  {
    id: "5",
    name: "Franchise E",
    owner_profession: "Retailer",
    location: "Miami",
    budget: "180000",
    motivation: "High growth potential",
    expectations: "Long-term partnership",
    connection_type: "Direct",
    requirement_stage: "In Progress",
    comments: "Optimistic about the future",
    email: "ownerE@example.com",
    mobile_number: "555-7777",
    city: "Miami",
    country: "USA",
  },
];

export const branches: Branch[] = [
  {
    id: "1",
    name: "Branch A",
    logo: "logoA.png",
    email: "branchA@example.com",
    address: "123 Market St, Anytown",
    mobile_number: "555-4444",
    website_url: "http://branchA.com",
    target_line: "Main Branch",
    country: "USA",
    institute_id: "INS001",
  },
  {
    id: "2",
    name: "Branch B",
    logo: "logoB.png",
    email: "branchB@example.com",
    address: "456 Elm St, Anycity",
    mobile_number: "555-5555",
    website_url: "http://branchB.com",
    target_line: "Satellite Branch",
    country: "Canada",
    institute_id: "INS002",
  },
  {
    id: "3",
    name: "Branch C",
    logo: "logoC.png",
    email: "branchC@example.com",
    address: "789 Pine St, Anyville",
    mobile_number: "555-6666",
    website_url: "http://branchC.com",
    target_line: "Secondary Branch",
    country: "UK",
    institute_id: "INS003",
  },
  {
    id: "4",
    name: "Branch D",
    logo: "logoD.png",
    email: "branchD@example.com",
    address: "321 Maple St, Anyborough",
    mobile_number: "555-7777",
    website_url: "http://branchD.com",
    target_line: "Main Branch",
    country: "Australia",
    institute_id: "INS004",
  },
  {
    id: "5",
    name: "Branch E",
    logo: "logoE.png",
    email: "branchE@example.com",
    address: "654 Oak St, Anyland",
    mobile_number: "555-8888",
    website_url: "http://branchE.com",
    target_line: "Main Branch",
    country: "India",
    institute_id: "INS005",
  },
];

// Example objects for PendingInstructor
export const pendingInstructors: PendingInstructor[] = [
  {
    id: "1",
    nid: "123456789",
    family_id: "FAM001",
    name: "John Doe",
    gender: "Male",
    date_of_birth: "1985-03-12",
    parent_name: "Robert Doe",
    email: "john.instructor@example.com",
    mobile_number: "555-1234",
    whatsapp_number: "555-5678",
    address: "123 University St, Anytown",
    religion: "Christianity",
    blood_group: "A+",
    diseases: "None",
    date_of_join: "2022-09-01",
    is_active: "Yes",
    currency: "USD",
    username: "john_doe",
    password: "securepassword123",
    faculty: "Computer Science",
    cv: "john_doe_cv.pdf",
    experience: "5 years teaching computer science",
    major: "Artificial Intelligence",
  },
  {
    id: "2",
    nid: "987654321",
    name: "Jane Smith",
    gender: "Female",
    date_of_birth: "1990-07-05",
    parent_name: "Sarah Smith",
    email: "jane.smith@example.com",
    mobile_number: "555-2345",
    whatsapp_number: "555-6789",
    address: "456 University Blvd, Anycity",
    date_of_join: "2021-05-15",
    is_active: "Yes",
    currency: "EUR",
    username: "jane_smith",
    password: "mypassword456",
    faculty: "Mathematics",
    cv: "jane_smith_cv.pdf",
    experience: "3 years teaching advanced calculus",
    major: "Algebra",
  },
  // Add 3 more PendingInstructor objects here...
];

// Example objects for Admin
export const admins: Admin[] = [
  {
    id: "1",
    nid: "1122334455",
    family_id: "FAM002",
    name: "Alice Brown",
    gender: "Female",
    date_of_birth: "1988-04-22",
    parent_name: "Margaret Brown",
    email: "alice.admin@example.com",
    mobile_number: "555-3456",
    whatsapp_number: "555-7890",
    address: "789 Admin St, Adminville",
    religion: "Islam",
    blood_group: "O+",
    diseases: "None",
    date_of_join: "2019-01-10",
    is_active: "Yes",
    promo_code: "ADMIN2023",
    currency: "GBP",
    username: "alice_brown",
    password: "adminpass123",
    role: "System Administrator",
    branch_id: "BR001",
  },
  {
    id: "2",
    nid: "2233445566",
    name: "Bob Williams",
    gender: "Male",
    date_of_birth: "1979-11-15",
    parent_name: "James Williams",
    email: "bob.admin@example.com",
    mobile_number: "555-4567",
    whatsapp_number: "555-8901",
    address: "123 Admin Ave, Admincity",
    date_of_join: "2018-03-20",
    is_active: "Yes",
    currency: "USD",
    username: "bob_williams",
    password: "secureadminpass",
    role: "IT Manager",
    branch_id: "BR002",
  },
  // Add 3 more Admin objects here...
];

// Example objects for Student
export const students: Student[] = [
  {
    id: "1",
    nid: "7788990011",
    family_id: "FAM003",
    name: "Charlie Green",
    gender: "Male",
    date_of_birth: "2008-09-10",
    parent_name: "Lucy Green",
    email: "charlie.student@example.com",
    mobile_number: "555-5678",
    whatsapp_number: "555-7890",
    address: "321 School Lane, Studycity",
    religion: "Judaism",
    blood_group: "B+",
    diseases: "None",
    date_of_join: "2023-01-05",
    is_active: "Yes",
    currency: "USD",
    username: "charlie_green",
    password: "studentpass123",
    discount: "10%",
    siblings: [],
    notes: "Highly active in sports",
    registration_num: "REG001",
    previous_school: "Greenwood School",
    has_laptop: true,
    is_orphan: false,
  },
  {
    id: "2",
    nid: "9900112233",
    name: "Emily White",
    gender: "Female",
    date_of_birth: "2007-05-18",
    parent_name: "John White",
    email: "emily.student@example.com",
    mobile_number: "555-6789",
    whatsapp_number: "555-8901",
    address: "456 Learning Blvd, Schooltown",
    date_of_join: "2022-08-12",
    is_active: "Yes",
    currency: "EUR",
    username: "emily_white",
    password: "mypassword789",
    discount: "15%",
    siblings: [],
    notes: "Excellent in science",
    registration_num: "REG002",
    previous_school: "Blue Valley Academy",
    has_laptop: true,
    is_orphan: true,
  },
  {
    id: "3",
    nid: "5544332211",
    name: "David Black",
    gender: "Male",
    date_of_birth: "2009-11-22",
    parent_name: "Catherine Black",
    email: "david.student@example.com",
    mobile_number: "555-7890",
    whatsapp_number: "555-9012",
    address: "789 Education St, Knowledgetown",
    date_of_join: "2021-09-10",
    is_active: "Yes",
    currency: "USD",
    username: "david_black",
    password: "studentpass456",
    discount: "5%",
    siblings: [],
    notes: "Needs improvement in math",
    registration_num: "REG003",
    previous_school: "Redwood High",
    has_laptop: false,
    is_orphan: false,
  },
  // Add 2 more Student objects here...
];

// Example objects for Parent
export const parents: Parent[] = [
  {
    id: "1",
    nid: "2233445566",
    family_id: "FAM001",
    name: "George Brown",
    gender: "Male",
    date_of_birth: "1975-02-15",
    parent_name: "Michael Brown",
    email: "george.parent@example.com",
    mobile_number: "555-1234",
    whatsapp_number: "555-5678",
    address: "456 Parent Ave, Cityville",
    religion: "Christianity",
    blood_group: "O+",
    diseases: "None",
    date_of_join: "2015-04-10",
    is_active: "Yes",
    currency: "USD",
    username: "george_brown",
    password: "parentpass123",
    education: "Bachelor's in Business Administration",
    profession: "Manager",
    occupation: "Office Manager",
    monthly_income: "5000 USD",
    children: [
      {
        id: "101",
        nid: "7788990011",
        family_id: "FAM001",
        name: "Charlie Brown",
        gender: "Male",
        date_of_birth: "2010-03-05",
        parent_name: "George Brown",
        email: "charlie.student@example.com",
        mobile_number: "555-2345",
        whatsapp_number: "555-6789",
        address: "456 Parent Ave, Cityville",
        date_of_join: "2021-09-01",
        is_active: "Yes",
        currency: "USD",
        username: "charlie_brown",
        password: "studentpass123",
        discount: "10%",
        siblings: [],
        notes: "Loves science",
        registration_num: "REG101",
        previous_school: "Primary School",
        has_laptop: true,
        is_orphan: false,
      },
    ],
  },
  {
    id: "2",
    nid: "3344556677",
    name: "Sara White",
    gender: "Female",
    date_of_birth: "1980-06-20",
    parent_name: "Anna White",
    email: "sara.parent@example.com",
    mobile_number: "555-3456",
    whatsapp_number: "555-7890",
    address: "789 Parent Blvd, Townsville",
    date_of_join: "2017-07-15",
    is_active: "Yes",
    currency: "EUR",
    username: "sara_white",
    password: "mypassword123",
    education: "Master's in Education",
    profession: "Teacher",
    occupation: "Math Teacher",
    monthly_income: "4000 EUR",
    children: [
      {
        id: "102",
        nid: "9900112233",
        family_id: "FAM002",
        name: "Emily White",
        gender: "Female",
        date_of_birth: "2007-05-18",
        parent_name: "Sara White",
        email: "emily.student@example.com",
        mobile_number: "555-4567",
        whatsapp_number: "555-8901",
        address: "789 Parent Blvd, Townsville",
        date_of_join: "2022-08-01",
        is_active: "Yes",
        currency: "EUR",
        username: "emily_white",
        password: "studentpass789",
        discount: "15%",
        siblings: [],
        notes: "Excellent in math",
        registration_num: "REG102",
        previous_school: "Junior High School",
        has_laptop: true,
        is_orphan: false,
      },
    ],
  },
  // Add 3 more Parent objects here...
];

// Example objects for Instructor
export const instructors: Instructor[] = [
  {
    id: "1",
    nid: "5566778899",
    family_id: "FAM003",
    name: "Jacob Martin",
    gender: "Male",
    date_of_birth: "1985-09-12",
    parent_name: "David Martin",
    email: "jacob.instructor@example.com",
    mobile_number: "555-5678",
    whatsapp_number: "555-7890",
    address: "123 Instructor Rd, Teacherville",
    religion: "Atheism",
    blood_group: "A+",
    diseases: "None",
    date_of_join: "2018-09-10",
    is_active: "Yes",
    currency: "USD",
    username: "jacob_martin",
    password: "instructorpass123",
    faculty: "Computer Science",
    cv: "jacob_martin_cv.pdf",
    experience: "7 years teaching software development",
    major: "Software Engineering",
  },
  {
    id: "2",
    nid: "6655443322",
    name: "Laura Green",
    gender: "Female",
    date_of_birth: "1988-11-22",
    parent_name: "Linda Green",
    email: "laura.instructor@example.com",
    mobile_number: "555-6789",
    whatsapp_number: "555-8901",
    address: "456 Instructor St, Knowledgetown",
    date_of_join: "2019-02-05",
    is_active: "Yes",
    currency: "EUR",
    username: "laura_green",
    password: "mypassword456",
    faculty: "Physics",
    cv: "laura_green_cv.pdf",
    experience: "5 years teaching quantum physics",
    major: "Astrophysics",
  },
  // Add 3 more Instructor objects here...
];

// Example objects for Employee
export const employees: Employee[] = [
  {
    id: "1",
    nid: "7788990011",
    family_id: "FAM004",
    name: "Thomas Blake",
    gender: "Male",
    date_of_birth: "1990-04-10",
    parent_name: "Martha Blake",
    email: "thomas.employee@example.com",
    mobile_number: "555-1234",
    whatsapp_number: "555-5678",
    address: "789 Employee Blvd, Worktown",
    religion: "Christianity",
    blood_group: "B+",
    diseases: "None",
    date_of_join: "2020-10-01",
    is_active: "Yes",
    currency: "USD",
    username: "thomas_blake",
    password: "employeepass123",
    salary: 4500,
    experience: "5 years in network administration",
    education: "Bachelor's in Information Technology",
    role: "Network Administrator",
  },
  {
    id: "2",
    nid: "1122334455",
    name: "Sophia Wilson",
    gender: "Female",
    date_of_birth: "1992-12-12",
    parent_name: "Robert Wilson",
    email: "sophia.employee@example.com",
    mobile_number: "555-2345",
    whatsapp_number: "555-6789",
    address: "123 Employee St, Jobville",
    date_of_join: "2021-05-20",
    is_active: "Yes",
    currency: "EUR",
    username: "sophia_wilson",
    password: "mypassword789",
    salary: 5000,
    experience: "4 years in human resources",
    education: "Master's in Business Administration",
    role: "HR Manager",
  },
  // Add 3 more Employee objects here...
];

// Example objects for Family
export const families: Family[] = [
  {
    id: "FAM001",
    father_id: "1",
    mother_id: "2",
    student_id: "101",
  },
  {
    id: "FAM002",
    father_id: "3",
    mother_id: "4",
    student_id: "102",
  },
  {
    id: "FAM003",
    father_id: "5",
    mother_id: "6",
    student_id: "103",
  },
  {
    id: "FAM004",
    father_id: "7",
    mother_id: "8",
    student_id: "104",
  },
  {
    id: "FAM005",
    father_id: "9",
    mother_id: "10",
    student_id: "105",
  },
];

// Example objects for Roles
export const roles: Roles[] = [
  {
    id: "ROLE001",
    name: "Admin",
  },
  {
    id: "ROLE002",
    name: "Instructor",
  },
  {
    id: "ROLE003",
    name: "Student",
  },
  {
    id: "ROLE004",
    name: "Parent",
  },
  {
    id: "ROLE005",
    name: "Employee",
  },
];

// Example objects for UserRoleMapping
export const userRoleMappings: UserRoleMapping[] = [
  {
    user_id: "1",
    role_id: "ROLE001", // Admin
  },
  {
    user_id: "2",
    role_id: "ROLE002", // Instructor
  },
  {
    user_id: "3",
    role_id: "ROLE003", // Student
  },
  {
    user_id: "4",
    role_id: "ROLE004", // Parent
  },
  {
    user_id: "5",
    role_id: "ROLE005", // Employee
  },
];

// Example objects for Program
export const programs: Program[] = [
  {
    id: "PROG001",
    name: "Computer Science Basics",
    levels: "Beginner, Intermediate, Advanced",
    price: "200 USD",
    description:
      "An introductory program covering fundamental concepts in computer science.",
  },
  {
    id: "PROG002",
    name: "Mathematics Mastery",
    levels: "Intermediate, Advanced",
    price: "150 USD",
    description:
      "A comprehensive program designed to enhance math skills and problem-solving.",
  },
  {
    id: "PROG003",
    name: "Creative Writing",
    levels: "Beginner, Intermediate",
    price: "100 USD",
    description:
      "A program to improve creative writing skills and storytelling.",
  },
  {
    id: "PROG004",
    name: "Physics for High School",
    levels: "Advanced",
    price: "250 USD",
    description: "An advanced program focusing on high school physics topics.",
  },
  {
    id: "PROG005",
    name: "Digital Marketing",
    levels: "Beginner, Intermediate, Advanced",
    price: "300 USD",
    description:
      "A detailed program covering all aspects of digital marketing and strategies.",
  },
];

// Example objects for Subject
export const subjects: Subject[] = [
  {
    id: "SUB001",
    name: "Introduction to Algorithms",
    mark: "90",
    track_id: "TRK001",
    program_id: "PROG001",
  },
  {
    id: "SUB002",
    name: "Linear Algebra",
    mark: "85",
    track_id: "TRK002",
    program_id: "PROG002",
  },
  {
    id: "SUB003",
    name: "Creative Writing Essentials",
    mark: "88",
    track_id: "TRK003",
    program_id: "PROG003",
  },
  {
    id: "SUB004",
    name: "Advanced Physics",
    mark: "92",
    track_id: "TRK004",
    program_id: "PROG004",
  },
  {
    id: "SUB005",
    name: "SEO Fundamentals",
    mark: "95",
    track_id: "TRK005",
    program_id: "PROG005",
  },
];

// Example objects for Track
export const tracks: Track[] = [
  {
    id: "TRK001",
    name: "Computer Science Track",
  },
  {
    id: "TRK002",
    name: "Mathematics Track",
  },
  {
    id: "TRK003",
    name: "Writing and Communication Track",
  },
  {
    id: "TRK004",
    name: "Science and Engineering Track",
  },
  {
    id: "TRK005",
    name: "Marketing and Business Track",
  },
];

// Example objects for Grade
export const grades: Grade[] = [
  {
    id: "GRD001",
    symbol: "A",
    status: "Pass",
    min_age: "10",
    max_age: "15",
  },
  {
    id: "GRD002",
    symbol: "B",
    status: "Pass",
    min_age: "15",
    max_age: "18",
  },
  {
    id: "GRD003",
    symbol: "C",
    status: "Pass",
    min_age: "8",
    max_age: "12",
  },
  {
    id: "GRD004",
    symbol: "D",
    status: "Fail",
    min_age: "5",
    max_age: "10",
  },
  {
    id: "GRD005",
    symbol: "F",
    status: "Fail",
    min_age: "12",
    max_age: "18",
  },
];

// Example objects for Assignment
export const assignments: Assignment[] = [
  {
    id: "ASSIGN001",
    url: "http://example.com/assignment1",
    due_date: "2024-10-15",
    attachments: "assignment1.pdf",
    description: "Complete the coding exercises in Chapter 3.",
    subject_id: "SUB001",
    sender_id: "INSTR001",
    class_id: "CLASS001",
  },
  {
    id: "ASSIGN002",
    url: "http://example.com/assignment2",
    due_date: "2024-11-01",
    attachments: "assignment2.docx",
    description: "Write an essay on modern digital marketing trends.",
    subject_id: "SUB002",
    sender_id: "INSTR002",
    class_id: "CLASS002",
  },
  {
    id: "ASSIGN003",
    url: "http://example.com/assignment3",
    due_date: "2024-10-22",
    attachments: "assignment3.pdf",
    description: "Solve the algebra problems from the worksheet.",
    subject_id: "SUB003",
    sender_id: "INSTR003",
    class_id: "CLASS003",
  },
  {
    id: "ASSIGN004",
    url: "http://example.com/assignment4",
    due_date: "2024-12-10",
    attachments: "assignment4.pdf",
    description: "Prepare a project on renewable energy.",
    subject_id: "SUB004",
    sender_id: "INSTR004",
    class_id: "CLASS004",
  },
  {
    id: "ASSIGN005",
    url: "http://example.com/assignment5",
    due_date: "2024-09-25",
    attachments: "assignment5.docx",
    description: "Create a website mockup using HTML and CSS.",
    subject_id: "SUB005",
    sender_id: "INSTR005",
    class_id: "CLASS005",
  },
];

// Example objects for AssignmentSubmission
export const assignmentSubmissions: AssignmentSubmission[] = [
  {
    id: "SUB001",
    url: "http://example.com/submission1",
    timestamp: "2024-10-13T10:30:00Z",
    evaluation: "Good work, but needs some corrections.",
    attachment: "submission1.pdf",
    subject_id: "SUB001",
    sender_id: "INSTR001",
    student_id: "STU001",
    class_id: "CLASS001",
  },
  {
    id: "SUB002",
    url: "http://example.com/submission2",
    timestamp: "2024-11-02T14:45:00Z",
    evaluation: "Excellent analysis of marketing trends.",
    attachment: "submission2.docx",
    subject_id: "SUB002",
    sender_id: "INSTR002",
    student_id: "STU002",
    class_id: "CLASS002",
  },
  {
    id: "SUB003",
    url: "http://example.com/submission3",
    timestamp: "2024-10-20T09:20:00Z",
    evaluation: "Well done. All problems solved correctly.",
    attachment: "submission3.pdf",
    subject_id: "SUB003",
    sender_id: "INSTR003",
    student_id: "STU003",
    class_id: "CLASS003",
  },
  {
    id: "SUB004",
    url: "http://example.com/submission4",
    timestamp: "2024-12-11T16:30:00Z",
    evaluation: "Innovative project, great presentation!",
    attachment: "submission4.pdf",
    subject_id: "SUB004",
    sender_id: "INSTR004",
    student_id: "STU004",
    class_id: "CLASS004",
  },
  {
    id: "SUB005",
    url: "http://example.com/submission5",
    timestamp: "2024-09-24T11:50:00Z",
    evaluation: "Creative design, but lacks responsive elements.",
    attachment: "submission5.docx",
    subject_id: "SUB005",
    sender_id: "INSTR005",
    student_id: "STU005",
    class_id: "CLASS005",
  },
];

// Example objects for Class
export const classes: Class[] = [
  {
    id: "CLASS001",
    name: "Introduction to Algorithms",
    fees: "500 USD",
    begin_date: "2024-09-01",
    end_date: "2024-12-01",
    program_id: "PROG001",
    instructor_id: "INSTR001",
  },
  {
    id: "CLASS002",
    name: "Digital Marketing Strategies",
    fees: "600 USD",
    begin_date: "2024-10-01",
    end_date: "2025-01-01",
    program_id: "PROG005",
    instructor_id: "INSTR002",
  },
  {
    id: "CLASS003",
    name: "Advanced Mathematics",
    fees: "550 USD",
    begin_date: "2024-08-15",
    end_date: "2024-11-15",
    program_id: "PROG002",
    instructor_id: "INSTR003",
  },
  {
    id: "CLASS004",
    name: "Physics for Engineers",
    fees: "700 USD",
    begin_date: "2024-07-01",
    end_date: "2024-10-01",
    program_id: "PROG004",
    instructor_id: "INSTR004",
  },
  {
    id: "CLASS005",
    name: "Web Development Basics",
    fees: "400 USD",
    begin_date: "2024-09-10",
    end_date: "2024-12-10",
    program_id: "PROG001",
    instructor_id: "INSTR005",
  },
];

// Example objects for ClassMapping
export const classMappings: ClassMapping[] = [
  {
    id: "CLASSMAP001",
    name: "Introduction to Algorithms",
    program_id: "PROG001",
    student_id: "STU001",
    instructor_id: "INSTR001",
  },
  {
    id: "CLASSMAP002",
    name: "Digital Marketing Strategies",
    program_id: "PROG005",
    student_id: "STU002",
    instructor_id: "INSTR002",
  },
  {
    id: "CLASSMAP003",
    name: "Advanced Mathematics",
    program_id: "PROG002",
    student_id: "STU003",
    instructor_id: "INSTR003",
  },
  {
    id: "CLASSMAP004",
    name: "Physics for Engineers",
    program_id: "PROG004",
    student_id: "STU004",
    instructor_id: "INSTR004",
  },
  {
    id: "CLASSMAP005",
    name: "Web Development Basics",
    program_id: "PROG001",
    student_id: "STU005",
    instructor_id: "INSTR005",
  },
];

// Example objects for Booking
export const bookings: Booking[] = [
  {
    id: "BOOK001",
    type: "Class",
    timestamp: "2024-09-15T10:00:00Z",
    booker: "Student John Doe",
  },
  {
    id: "BOOK002",
    type: "Event",
    timestamp: "2024-09-16T14:30:00Z",
    booker: "Parent Jane Smith",
  },
  {
    id: "BOOK003",
    type: "Consultation",
    timestamp: "2024-09-17T09:00:00Z",
    booker: "Instructor Emily White",
  },
  {
    id: "BOOK004",
    type: "Class",
    timestamp: "2024-09-18T11:45:00Z",
    booker: "Student Alice Brown",
  },
  {
    id: "BOOK005",
    type: "Workshop",
    timestamp: "2024-09-19T13:00:00Z",
    booker: "Employee Thomas Blake",
  },
];

// Example objects for Subscription
export const subscriptions: Subscription[] = [
  {
    id: "SUB001",
    type: "Monthly",
    class_id: "CLASS001",
    transaction_id: "TXN001",
    screenshot: "screenshot1.jpg",
    begin_date: "2024-09-01",
    end_date: "2024-09-30",
    paid_by: "Credit Card",
    student_id: "STU001",
  },
  {
    id: "SUB002",
    type: "Annual",
    class_id: "CLASS002",
    transaction_id: "TXN002",
    screenshot: "screenshot2.jpg",
    begin_date: "2024-01-01",
    end_date: "2024-12-31",
    paid_by: "Bank Transfer",
    student_id: "STU002",
  },
  {
    id: "SUB003",
    type: "Semester",
    class_id: "CLASS003",
    transaction_id: "TXN003",
    screenshot: "screenshot3.jpg",
    begin_date: "2024-08-15",
    end_date: "2024-12-15",
    paid_by: "PayPal",
    student_id: "STU003",
  },
  {
    id: "SUB004",
    type: "Monthly",
    class_id: "CLASS004",
    transaction_id: "TXN004",
    screenshot: "screenshot4.jpg",
    begin_date: "2024-09-01",
    end_date: "2024-09-30",
    paid_by: "Credit Card",
    student_id: "STU004",
  },
  {
    id: "SUB005",
    type: "Weekly",
    class_id: "CLASS005",
    transaction_id: "TXN005",
    screenshot: "screenshot5.jpg",
    begin_date: "2024-09-05",
    end_date: "2024-09-12",
    paid_by: "Cash",
    student_id: "STU005",
  },
];

// Example objects for Attendance
export const attendance: Attendance[] = [
  {
    id: "ATT001",
    status: "Present",
    date: "2024-09-15",
    day: "Monday",
    class_id: "CLASS001",
    student_Id: "STU001",
  },
  {
    id: "ATT002",
    status: "Absent",
    date: "2024-09-16",
    day: "Tuesday",
    class_id: "CLASS002",
    student_Id: "STU002",
  },
  {
    id: "ATT003",
    status: "Present",
    date: "2024-09-17",
    day: "Wednesday",
    class_id: "CLASS003",
    student_Id: "STU003",
  },
  {
    id: "ATT004",
    status: "Late",
    date: "2024-09-18",
    day: "Thursday",
    class_id: "CLASS004",
    student_Id: "STU004",
  },
  {
    id: "ATT005",
    status: "Present",
    date: "2024-09-19",
    day: "Friday",
    class_id: "CLASS005",
    student_Id: "STU005",
  },
];

// Example objects for EmployeeAttendance
export const employeeAttendances: EmployeeAttendance[] = [
  {
    id: "EMPATT001",
    role: "Manager",
    status: "Present",
    date: "2024-09-15",
    day: "Monday",
    check_in: "09:00 AM",
    check_out: "05:00 PM",
    duration: "8 hours",
    employee_id: "EMP001",
  },
  {
    id: "EMPATT002",
    role: "HR",
    status: "Present",
    date: "2024-09-16",
    day: "Tuesday",
    check_in: "09:15 AM",
    check_out: "05:00 PM",
    duration: "7 hours 45 minutes",
    employee_id: "EMP002",
  },
  {
    id: "EMPATT003",
    role: "Developer",
    status: "Late",
    date: "2024-09-17",
    day: "Wednesday",
    check_in: "09:30 AM",
    check_out: "06:00 PM",
    duration: "8 hours 30 minutes",
    employee_id: "EMP003",
  },
  {
    id: "EMPATT004",
    role: "Designer",
    status: "Absent",
    date: "2024-09-18",
    day: "Thursday",
    check_in: "N/A",
    check_out: "N/A",
    duration: "0 hours",
    employee_id: "EMP004",
  },
  {
    id: "EMPATT005",
    role: "Support Staff",
    status: "Present",
    date: "2024-09-19",
    day: "Friday",
    check_in: "08:45 AM",
    check_out: "04:45 PM",
    duration: "8 hours",
    employee_id: "EMP005",
  },
];

// Example objects for FreeSession
export const freeSessions: FreeSession[] = [
  {
    id: "FS001",
    name: "Intro to Programming",
    url: "http://example.com/free-session1",
    timestamp: "2024-09-10T10:00:00Z",
    class_id: "CLASS001",
    instructor_id: "INSTR001",
  },
  {
    id: "FS002",
    name: "Basics of Algebra",
    url: "http://example.com/free-session2",
    timestamp: "2024-09-11T11:00:00Z",
    class_id: "CLASS002",
    instructor_id: "INSTR002",
  },
  {
    id: "FS003",
    name: "Digital Marketing Overview",
    url: "http://example.com/free-session3",
    timestamp: "2024-09-12T12:00:00Z",
    class_id: "CLASS003",
    instructor_id: "INSTR003",
  },
  {
    id: "FS004",
    name: "Creative Writing 101",
    url: "http://example.com/free-session4",
    timestamp: "2024-09-13T01:00:00Z",
    class_id: "CLASS004",
    instructor_id: "INSTR004",
  },
  {
    id: "FS005",
    name: "Physics for Beginners",
    url: "http://example.com/free-session5",
    timestamp: "2024-09-14T02:00:00Z",
    class_id: "CLASS005",
    instructor_id: "INSTR005",
  },
];

// Example objects for AssignedFreeSession
export const assignedFreeSessions: AssignedFreeSession[] = [
  {
    id: "AFS001",
    whatsapp: "+1234567890",
    grade: "A",
    has_laptop: true,
    mobile_number: "+1234567890",
    timestamp: "2024-09-10T10:30:00Z",
    session_id: "FS001",
    parent_id: "PAR001",
    class_id: "CLASS001",
    student_id: "STU001",
  },
  {
    id: "AFS002",
    whatsapp: "+0987654321",
    grade: "B",
    has_laptop: false,
    mobile_number: "+0987654321",
    timestamp: "2024-09-11T11:30:00Z",
    session_id: "FS002",
    parent_id: "PAR002",
    class_id: "CLASS002",
    student_id: "STU002",
  },
  {
    id: "AFS003",
    whatsapp: "+1111222233",
    grade: "A",
    has_laptop: true,
    mobile_number: "+1111222233",
    timestamp: "2024-09-12T12:30:00Z",
    session_id: "FS003",
    parent_id: "PAR003",
    class_id: "CLASS003",
    student_id: "STU003",
  },
  {
    id: "AFS004",
    whatsapp: "+2222333344",
    grade: "C",
    has_laptop: true,
    mobile_number: "+2222333344",
    timestamp: "2024-09-13T01:30:00Z",
    session_id: "FS004",
    parent_id: "PAR004",
    class_id: "CLASS004",
    student_id: "STU004",
  },
  {
    id: "AFS005",
    whatsapp: "+3333444455",
    grade: "B",
    has_laptop: false,
    mobile_number: "+3333444455",
    timestamp: "2024-09-14T02:30:00Z",
    session_id: "FS005",
    parent_id: "PAR005",
    class_id: "CLASS005",
    student_id: "STU005",
  },
];

// Example objects for AttendedFreeSession
export const attendedFreeSessions: AttendedFreeSession[] = [
  {
    id: "ATFS001",
    name: "Intro to Programming",
    status: "Completed",
    timestamp: "2024-09-10T11:30:00Z",
    session_id: "FS001",
    parent_id: "PAR001",
    class_id: "CLASS001",
    student_id: "STU001",
  },
  {
    id: "ATFS002",
    name: "Basics of Algebra",
    status: "Missed",
    timestamp: "2024-09-11T12:30:00Z",
    session_id: "FS002",
    parent_id: "PAR002",
    class_id: "CLASS002",
    student_id: "STU002",
  },
  {
    id: "ATFS003",
    name: "Digital Marketing Overview",
    status: "Completed",
    timestamp: "2024-09-12T01:30:00Z",
    session_id: "FS003",
    parent_id: "PAR003",
    class_id: "CLASS003",
    student_id: "STU003",
  },
  {
    id: "ATFS004",
    name: "Creative Writing 101",
    status: "Completed",
    timestamp: "2024-09-13T02:30:00Z",
    session_id: "FS004",
    parent_id: "PAR004",
    class_id: "CLASS004",
    student_id: "STU004",
  },
  {
    id: "ATFS005",
    name: "Physics for Beginners",
    status: "Missed",
    timestamp: "2024-09-14T03:30:00Z",
    session_id: "FS005",
    parent_id: "PAR005",
    class_id: "CLASS005",
    student_id: "STU005",
  },
];

// Example objects for Fee
export const fees: Fee[] = [
  {
    id: "FEE001",
    type: "Tuition",
    target_role: "Student",
    amount: "500 USD",
  },
  {
    id: "FEE002",
    type: "Registration",
    target_role: "Parent",
    amount: "100 USD",
  },
  {
    id: "FEE003",
    type: "Lab Fee",
    target_role: "Student",
    amount: "50 USD",
  },
  {
    id: "FEE004",
    type: "Activity Fee",
    target_role: "Student",
    amount: "30 USD",
  },
  {
    id: "FEE005",
    type: "Membership",
    target_role: "Instructor",
    amount: "200 USD",
  },
];

// Example objects for Contact
export const contacts: Contact[] = [
  {
    id: "CONTACT001",
    mobile_number: "+1234567890",
    name: "John Doe",
    image: "john_doe.jpg",
    host_id: "HOST001",
  },
  {
    id: "CONTACT002",
    mobile_number: "+0987654321",
    name: "Jane Smith",
    image: "jane_smith.jpg",
    host_id: "HOST002",
  },
  {
    id: "CONTACT003",
    mobile_number: "+1122334455",
    name: "Michael Brown",
    image: "michael_brown.jpg",
    host_id: "HOST003",
  },
  {
    id: "CONTACT004",
    mobile_number: "+5566778899",
    name: "Emily White",
    image: "emily_white.jpg",
    host_id: "HOST004",
  },
  {
    id: "CONTACT005",
    mobile_number: "+6677889900",
    name: "David Green",
    image: "david_green.jpg",
    host_id: "HOST005",
  },
];

// Example objects for Card
export const cards: Card[] = [
  {
    id: "CARD001",
    number: "1234-5678-9012-3456",
    holder: "John Doe",
    expiration_date: "12/25",
    cvv: "123",
    user_id: "USER001",
  },
  {
    id: "CARD002",
    number: "9876-5432-1098-7654",
    holder: "Jane Smith",
    expiration_date: "11/24",
    cvv: "456",
    user_id: "USER002",
  },
  {
    id: "CARD003",
    number: "5678-1234-5678-1234",
    holder: "Michael Brown",
    expiration_date: "10/23",
    cvv: "789",
    user_id: "USER003",
  },
  {
    id: "CARD004",
    number: "4321-8765-4321-8765",
    holder: "Emily White",
    expiration_date: "09/26",
    cvv: "101",
    user_id: "USER004",
  },
  {
    id: "CARD005",
    number: "6789-2345-6789-2345",
    holder: "David Green",
    expiration_date: "08/27",
    cvv: "202",
    user_id: "USER005",
  },
];

// Example objects for Schedules
export const schedules: Schedules[] = [
  {
    id: "SCHED001",
    name: "Math Class",
    type: "Lecture",
    url: "http://example.com/schedule1",
    timestamp: "2024-09-10T10:00:00Z",
    instructor_id: "INSTR001",
    class_id: "CLASS001",
  },
  {
    id: "SCHED002",
    name: "Science Class",
    type: "Workshop",
    url: "http://example.com/schedule2",
    timestamp: "2024-09-11T11:00:00Z",
    instructor_id: "INSTR002",
    class_id: "CLASS002",
  },
  {
    id: "SCHED003",
    name: "History Class",
    type: "Lecture",
    url: "http://example.com/schedule3",
    timestamp: "2024-09-12T12:00:00Z",
    instructor_id: "INSTR003",
    class_id: "CLASS003",
  },
  {
    id: "SCHED004",
    name: "Art Class",
    type: "Workshop",
    url: "http://example.com/schedule4",
    timestamp: "2024-09-13T01:00:00Z",
    instructor_id: "INSTR004",
    class_id: "CLASS004",
  },
  {
    id: "SCHED005",
    name: "Music Class",
    type: "Lecture",
    url: "http://example.com/schedule5",
    timestamp: "2024-09-14T02:00:00Z",
    instructor_id: "INSTR005",
    class_id: "CLASS005",
  },
];

// Example objects for InstructorCalled
export const instructorCalled: InstructorCalled[] = [
  {
    id: "CALL001",
    url: "http://example.com/call1",
    timestamp: "2024-09-15T10:00:00Z",
    parent_id: "PAR001",
    student_id: "STU001",
    instructor_id: "INSTR001",
    class_id: "CLASS001",
  },
  {
    id: "CALL002",
    url: "http://example.com/call2",
    timestamp: "2024-09-16T11:00:00Z",
    parent_id: "PAR002",
    student_id: "STU002",
    instructor_id: "INSTR002",
    class_id: "CLASS002",
  },
  {
    id: "CALL003",
    url: "http://example.com/call3",
    timestamp: "2024-09-17T12:00:00Z",
    parent_id: "PAR003",
    student_id: "STU003",
    instructor_id: "INSTR003",
    class_id: "CLASS003",
  },
  {
    id: "CALL004",
    url: "http://example.com/call4",
    timestamp: "2024-09-18T01:00:00Z",
    parent_id: "PAR004",
    student_id: "STU004",
    instructor_id: "INSTR004",
    class_id: "CLASS004",
  },
  {
    id: "CALL005",
    url: "http://example.com/call5",
    timestamp: "2024-09-19T02:00:00Z",
    parent_id: "PAR005",
    student_id: "STU005",
    instructor_id: "INSTR005",
    class_id: "CLASS005",
  },
];
