import { studentsColumns } from "@/components/pes-custom/table-columns/studentsColumns";
import { DataTable } from "@/components/ui/data-table";
import { Student } from "@/lib/types";
import React from "react";

async function getData(): Promise<Student[]> {
  // Fetch data from your API here.
  // Must fit the type definition to be inserted into the table
  return [
    {
      id: "S001",
      nid: "N10001",
      family_id: "F1001",
      name: "Emily Parker",
      gender: "Female",
      date_of_birth: "2010-05-15",
      parent_name: "John Parker",
      email: "emily.parker@example.com",
      mobile_number: "1234567890",
      whatsapp_number: "1234567890",
      address: "101 Maple St, Cityville",
      date_of_join: "2020-09-01",
      is_active: "Yes",
      password: "emilypass123",
      discount: "10%",
      siblings: [],
      notes: "Excellent student with high performance.",
      registration_num: "REG202101",
      previous_school: "City Elementary School",
      has_laptop: true,
      is_orphan: false,
    },
    {
      id: "S002",
      nid: "N10002",
      name: "Oliver Brown",
      gender: "Male",
      date_of_birth: "2009-08-25",
      parent_name: "Sarah Brown",
      email: "oliver.brown@example.com",
      mobile_number: "0987654321",
      whatsapp_number: "0987654321",
      address: "202 Oak St, Townsville",
      date_of_join: "2021-01-10",
      is_active: "Yes",
      password: "oliverpass123",
      discount: "15%",
      siblings: [],
      notes: "Needs support in math.",
      registration_num: "REG202102",
      previous_school: "Townville Junior School",
      has_laptop: false,
      is_orphan: false,
    },
    {
      id: "S003",
      nid: "N10003",
      name: "Sophia Martinez",
      gender: "Female",
      date_of_birth: "2011-12-30",
      parent_name: "Carlos Martinez",
      email: "sophia.martinez@example.com",
      mobile_number: "9876543210",
      whatsapp_number: "9876543210",
      address: "303 Birch St, Lakeside",
      date_of_join: "2020-05-15",
      is_active: "Yes",
      password: "sophiapass123",
      discount: "20%",
      siblings: [],
      notes: "Talented in arts and music.",
      registration_num: "REG202103",
      previous_school: "Lakeside Elementary",
      has_laptop: true,
      is_orphan: false,
    },
    {
      id: "S004",
      nid: "N10004",
      family_id: "F1002",
      name: "Liam Johnson",
      gender: "Male",
      date_of_birth: "2008-07-12",
      parent_name: "Michael Johnson",
      email: "liam.johnson@example.com",
      mobile_number: "1122334455",
      whatsapp_number: "1122334455",
      address: "404 Cedar St, Metropolis",
      date_of_join: "2019-09-20",
      is_active: "Yes",
      password: "liampass123",
      discount: "25%",
      siblings: [],
      notes: "Great in sports and physical education.",
      registration_num: "REG202104",
      previous_school: "Metropolis Junior School",
      has_laptop: true,
      is_orphan: false,
    },
    {
      id: "S005",
      nid: "N10005",
      family_id: "F1003",
      name: "Isabella Taylor",
      gender: "Female",
      date_of_birth: "2009-11-03",
      parent_name: "Laura Taylor",
      email: "isabella.taylor@example.com",
      mobile_number: "2233445566",
      whatsapp_number: "2233445566",
      address: "505 Pine St, Smalltown",
      date_of_join: "2021-03-05",
      is_active: "Yes",
      password: "isabellapass123",
      discount: "5%",
      siblings: [],
      notes: "Good behavior, needs improvement in science.",
      registration_num: "REG202105",
      previous_school: "Smalltown School",
      has_laptop: false,
      is_orphan: true,
    },
    {
      id: "S006",
      nid: "N10006",
      name: "James Wilson",
      gender: "Male",
      date_of_birth: "2010-02-14",
      parent_name: "Helen Wilson",
      email: "james.wilson@example.com",
      mobile_number: "3344556677",
      whatsapp_number: "3344556677",
      address: "606 Willow St, Lakeview",
      date_of_join: "2020-12-10",
      is_active: "Yes",
      password: "jamespass123",
      discount: "10%",
      siblings: [],
      notes: "Needs help with focus and concentration.",
      registration_num: "REG202106",
      previous_school: "Lakeview Junior High",
      has_laptop: false,
      is_orphan: false,
    },
    {
      id: "S007",
      nid: "N10007",
      name: "Ava White",
      gender: "Female",
      date_of_birth: "2012-09-28",
      parent_name: "John White",
      email: "ava.white@example.com",
      mobile_number: "4455667788",
      whatsapp_number: "4455667788",
      address: "707 Elm St, Cityville",
      date_of_join: "2021-07-01",
      is_active: "Yes",
      password: "avapass123",
      discount: "30%",
      siblings: [],
      notes: "Creative and loves reading.",
      registration_num: "REG202107",
      previous_school: "Cityville Junior School",
      has_laptop: true,
      is_orphan: true,
    },
    {
      id: "S008",
      nid: "N10008",
      name: "Mason Lee",
      gender: "Male",
      date_of_birth: "2007-05-20",
      parent_name: "David Lee",
      email: "mason.lee@example.com",
      mobile_number: "5566778899",
      whatsapp_number: "5566778899",
      address: "808 Pine St, Villagetown",
      date_of_join: "2018-05-15",
      is_active: "Yes",
      password: "masonpass123",
      discount: "15%",
      siblings: [],
      notes: "Excellent leadership skills.",
      registration_num: "REG202108",
      previous_school: "Villagetown Junior High",
      has_laptop: true,
      is_orphan: false,
    },
    {
      id: "S009",
      nid: "N10009",
      name: "Charlotte King",
      gender: "Female",
      date_of_birth: "2011-01-18",
      parent_name: "Jessica King",
      email: "charlotte.king@example.com",
      mobile_number: "6677889900",
      whatsapp_number: "6677889900",
      address: "909 Maple St, Riverwood",
      date_of_join: "2020-01-15",
      is_active: "Yes",
      password: "charlottepass123",
      discount: "20%",
      siblings: [],
      notes: "Needs more focus on language skills.",
      registration_num: "REG202109",
      previous_school: "Riverwood Elementary",
      has_laptop: true,
      is_orphan: false,
    },
    {
      id: "S010",
      nid: "N10010",
      name: "Ethan Harris",
      gender: "Male",
      date_of_birth: "2008-04-10",
      parent_name: "Amanda Harris",
      email: "ethan.harris@example.com",
      mobile_number: "7788990011",
      whatsapp_number: "7788990011",
      address: "1010 Cedar St, Greenfield",
      date_of_join: "2019-03-01",
      is_active: "Yes",
      password: "ethanpass123",
      discount: "5%",
      siblings: [],
      notes: "Hardworking, strong in science and math.",
      registration_num: "REG202110",
      previous_school: "Greenfield Middle School",
      has_laptop: true,
      is_orphan: false,
    },
  ];
}

const page = async () => {
  const data = await getData();

  return (
    <div className="flex w-full flex-col">
      <h3 className="text-h3">Students</h3>
      <DataTable columns={studentsColumns} data={data} />
    </div>
  );
};

export default page;
